services:
  kestra:
    image: kestra/kestra:latest-full
    command: server local
    ports:
      - "8080:8080"
    environment:
      KESTRA_CONFIGURATION: |
        kestra:
          storage:
            type: local
            local:
              base-path: /app/storage
    volumes:
      - ./kestra/storage:/app/storage
      # This maps your local file to a fixed path inside the container
      - ./keys/gcp_key.json:/app/gcp_key.json